### ISSUE TITLE
Your issue is unrelated to this library.

### ISSUE THREAD

**Issue by priyank1987225** [pangz-lab/coingecko-api#4]
Your issue is unrelated to this library.
I assume you're talking about mining.
You can check the faqs here.

https://pangz-lab.github.io/verusminer/

_Originally posted by @pangz-lab in https://github.com/pangz-lab/coingecko-api/issues/3#issuecomment-2528502282_

**Comment by priyank1987225** [comment]
No any one help me till now kindly call arrange or email my registered email also mobile number

**Comment by pangz-lab** [comment]
What help do you need?
